# Generated by Django 5.2.1 on 2025-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Phòng khám Medionco', max_length=255, verbose_name='tên phòng khám')),
                ('address', models.TextField(blank=True, null=True, verbose_name='địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email phòng khám')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logo/', verbose_name='logo phòng khám')),
            ],
            options={
                'verbose_name': 'cài đặt phòng khám',
                'verbose_name_plural': 'cài đặt phòng khám',
            },
        ),
    ]
