# Generated by Django 5.2.1 on 2025-05-17 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='tên mẫu xét nghiệm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='người tạo')),
            ],
            options={
                'verbose_name': 'mẫu xét nghiệm',
                'verbose_name_plural': 'danh sách mẫu xét nghiệm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='tên chỉ số')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='đơn vị')),
                ('normal_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='giá trị bình thường (min)')),
                ('normal_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='giá trị bình thường (max)')),
                ('field_order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị của chỉ số trong mẫu', verbose_name='thứ tự hiển thị')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='labtests.labtesttemplate', verbose_name='mẫu xét nghiệm cha')),
            ],
            options={
                'verbose_name': 'chỉ số của mẫu xét nghiệm',
                'verbose_name_plural': 'các chỉ số của mẫu xét nghiệm',
                'ordering': ['template', 'field_order', 'field_name'],
            },
        ),
    ]
