# Generated by Django 5.2.1 on 2025-05-23 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('print_status', models.CharField(default='Chưa in', max_length=20, verbose_name='Trạng thái in')),
                ('last_print_date', models.DateTimeField(blank=True, null=True, verbose_name='Lần in cuối')),
                ('latest_version', models.PositiveIntegerField(default=1, verbose_name='Phiên bản mới nhất')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_created', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='medical_records.medicalrecord', verbose_name='Bệnh án liên quan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Phiếu xét nghiệm',
                'verbose_name_plural': 'Danh sách phiếu xét nghiệm',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LabTestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('version_number', models.PositiveIntegerField(verbose_name='Phiên bản')),
                ('change_reason', models.TextField(blank=True, verbose_name='Lý do thay đổi')),
                ('is_post_print', models.BooleanField(default=False, verbose_name='Sửa sau in')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian thay đổi')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='labtests.labtest', verbose_name='Phiếu xét nghiệm')),
            ],
            options={
                'verbose_name': 'Phiên bản phiếu xét nghiệm',
                'verbose_name_plural': 'Danh sách phiên bản phiếu xét nghiệm',
                'ordering': ('-version_number',),
                'abstract': False,
                'unique_together': {('lab_test', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Loại xét nghiệm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Loại xét nghiệm',
                'verbose_name_plural': 'Danh sách loại xét nghiệm',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtests.testcategory', verbose_name='Loại xét nghiệm'),
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên xét nghiệm')),
                ('reference_range', models.CharField(blank=True, max_length=100, verbose_name='Khoảng tham chiếu')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labtests.testcategory', verbose_name='Loại xét nghiệm')),
            ],
            options={
                'verbose_name': 'Mục xét nghiệm',
                'verbose_name_plural': 'Danh sách mục xét nghiệm',
                'ordering': ('order',),
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LabTestResultValueVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Giá trị')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('lab_test_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_values', to='labtests.labtestversion', verbose_name='Phiên bản phiếu')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtests.testitem', verbose_name='Mục xét nghiệm')),
            ],
            options={
                'verbose_name': 'Kết quả xét nghiệm (snapshot)',
                'verbose_name_plural': 'Danh sách kết quả xét nghiệm (snapshot)',
                'unique_together': {('lab_test_version', 'item')},
            },
        ),
        migrations.CreateModel(
            name='LabTestResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Giá trị')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labtests.labtest', verbose_name='Phiếu xét nghiệm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='labtests.testitem', verbose_name='Mục xét nghiệm')),
            ],
            options={
                'verbose_name': 'Kết quả xét nghiệm',
                'verbose_name_plural': 'Danh sách kết quả xét nghiệm',
                'unique_together': {('lab_test', 'item')},
            },
        ),
    ]
