# Generated by Django 5.2.1 on 2025-05-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
        ('medical_records', '0002_alter_medicalrecord_diagnosis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PRINTED', 'Đã in')], default='PENDING', max_length=20, verbose_name='trạng thái in')),
                ('last_print_date', models.DateTimeField(blank=True, null=True, verbose_name='ngày in sau cùng')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày yêu cầu')),
                ('results_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='kết quả cập nhật lúc')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='medical_records.medicalrecord', verbose_name='hồ sơ bệnh án')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_requested', to=settings.AUTH_USER_MODEL, verbose_name='người yêu cầu')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='labtests.labtesttemplate', verbose_name='mẫu xét nghiệm áp dụng')),
            ],
            options={
                'verbose_name': 'phiếu xét nghiệm',
                'verbose_name_plural': 'danh sách phiếu xét nghiệm',
                'ordering': ['-requested_at'],
            },
        ),
    ]
