# Generated by Django 5.2.1 on 2025-05-17 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0002_labtest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='giá trị kết quả')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ghi chú/bình luận')),
                ('entered_at', models.DateTimeField(auto_now=True, verbose_name='thời điểm nhập/sửa')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_values_entered', to=settings.AUTH_USER_MODEL, verbose_name='người nhập/sửa')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_values', to='labtests.labtest', verbose_name='phiếu xét nghiệm liên quan')),
                ('template_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_values', to='labtests.labtesttemplatefield', verbose_name='chỉ số xét nghiệm')),
            ],
            options={
                'verbose_name': 'giá trị kết quả xét nghiệm',
                'verbose_name_plural': 'các giá trị kết quả xét nghiệm',
                'ordering': ['lab_test', 'template_field__field_order'],
                'unique_together': {('lab_test', 'template_field')},
            },
        ),
    ]
