# Generated by Django 5.2.1 on 2025-05-17 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0003_labtestresultvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='số phiên bản')),
                ('result_snapshot', models.TextField(blank=True, null=True, verbose_name='bản ghi kết quả (snapshot/JSON/PDF link)')),
                ('is_post_print', models.BooleanField(default=False, verbose_name='chỉnh sửa sau khi in')),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='lý do thay đổi')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='thời điểm thay đổi')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='người thay đổi')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='labtests.labtest', verbose_name='phiếu xét nghiệm gốc')),
            ],
            options={
                'verbose_name': 'phiên bản phiếu xét nghiệm',
                'verbose_name_plural': 'các phiên bản phiếu xét nghiệm',
                'ordering': ['lab_test', '-version_number'],
                'unique_together': {('lab_test', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='latest_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_lab_test', to='labtests.labtestversion', verbose_name='phiên bản mới nhất'),
        ),
    ]
