# Generated by Django 5.2.1 on 2025-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0004_labtestversion_labtest_latest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtesttemplatefield',
            name='reference_range_text',
            field=models.CharField(blank=True, help_text='Ví dụ: Âm tính, <10.0, Nam: 60-120 Nữ: 40-100', max_length=255, null=True, verbose_name='khoảng tham chiếu (dạng text)'),
        ),
        migrations.AddField(
            model_name='labtesttemplatefield',
            name='result_guidance',
            field=models.CharField(blank=True, help_text='Nhập hướng dẫn, giá trị mẫu, hoặc placeholder cho ô kết quả khi thực hiện xét nghiệm.', max_length=255, null=True, verbose_name='hướng dẫn/placeholder kết quả'),
        ),
    ]
