# Generated by Django 5.2.1 on 2025-05-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0005_labtesttemplatefield_reference_range_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='ID Phiếu Xét nghiệm'),
        ),
    ]
