# Generated by Django 5.2.1 on 2025-05-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='ngày khám')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='chẩn đoán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ghi chú của bác sĩ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_created', to=settings.AUTH_USER_MODEL, verbose_name='người tạo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='bệnh nhân')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_updated', to=settings.AUTH_USER_MODEL, verbose_name='người cập nhật')),
            ],
            options={
                'verbose_name': 'hồ sơ bệnh án',
                'verbose_name_plural': 'danh sách hồ sơ bệnh án',
                'ordering': ['-record_date', 'patient'],
            },
        ),
    ]
