# Generated by Django 5.2.1 on 2025-05-16 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='chẩn đoán (hiện hành)'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ghi chú của bác sĩ (hiện hành)'),
        ),
        migrations.CreateModel(
            name='MedicalRecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='số phiên bản')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='chẩn đoán (phiên bản)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ghi chú của bác sĩ (phiên bản)')),
                ('is_post_print', models.BooleanField(default=False, verbose_name='chỉnh sửa sau khi in')),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='lý do thay đổi')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='thời điểm thay đổi')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='người thay đổi')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='medical_records.medicalrecord', verbose_name='hồ sơ bệnh án gốc')),
            ],
            options={
                'verbose_name': 'phiên bản hồ sơ bệnh án',
                'verbose_name_plural': 'các phiên bản hồ sơ bệnh án',
                'ordering': ['medical_record', '-version_number'],
                'unique_together': {('medical_record', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='latest_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_record', to='medical_records.medicalrecordversion', verbose_name='phiên bản mới nhất'),
        ),
    ]
