# Generated by Django 5.2.1 on 2025-05-20 03:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày khám'),
        ),
        migrations.CreateModel(
            name='MedicalRecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('version_number', models.PositiveIntegerField(verbose_name='Phiên bản')),
                ('change_reason', models.TextField(blank=True, verbose_name='Lý do thay đổi')),
                ('is_post_print', models.BooleanField(default=False, verbose_name='Sửa sau in')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian thay đổi')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Chẩn đoán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='medical_records.medicalrecord', verbose_name='Bệnh án')),
            ],
            options={
                'verbose_name': 'Phiên bản bệnh án',
                'verbose_name_plural': 'Danh sách phiên bản bệnh án',
                'ordering': ('-version_number',),
                'abstract': False,
                'unique_together': {('medical_record', 'version_number')},
            },
        ),
    ]
