# Generated by Django 5.2.1 on 2025-05-22 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_alter_medicalrecord_record_date_medicalrecordversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ('-record_date',), 'verbose_name': 'Phiếu khám', 'verbose_name_plural': 'Danh sách phiếu khám'},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Đã hoàn thành'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(default=1, verbose_name='Triệu chứng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(default=1, verbose_name='Kế hoạch điều trị'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(verbose_name='Chẩn đoán'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='Tên thuốc')),
                ('dosage', models.CharField(max_length=100, verbose_name='Liều dùng')),
                ('frequency', models.CharField(max_length=100, verbose_name='Tần suất')),
                ('duration', models.CharField(max_length=100, verbose_name='Thời gian')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.prescription')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
                'ordering': ['created_at'],
            },
        ),
    ]
