# Generated by Django 5.2.1 on 2025-05-17 04:16

import apps.attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID đối tượng liên quan')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to=apps.attachments.models.get_attachment_upload_path, verbose_name='tệp đính kèm')),
                ('file_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='đường dẫn file (URL)')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='tên file hiển thị')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='loại file (MIME type)')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='kích thước file (bytes)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='mô tả ngắn')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tải lên')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='loại đối tượng liên quan')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='người tải lên')),
            ],
            options={
                'verbose_name': 'tệp đính kèm',
                'verbose_name_plural': 'danh sách tệp đính kèm',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_ddd303_idx')],
            },
        ),
    ]
