# Generated by Django 5.2.1 on 2025-05-17 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID đối tượng bị tác động')),
                ('action', models.CharField(choices=[('CREATED', 'Đã tạo'), ('UPDATED', 'Đã cập nhật'), ('DELETED', 'Đã xóa'), ('VIEWED', 'Đã xem'), ('PRINTED', 'Đã in'), ('LOGGED_IN', 'Đăng nhập'), ('LOGGED_OUT', 'Đăng xuất')], db_index=True, max_length=50, verbose_name='hành động')),
                ('details', models.TextField(blank=True, null=True, verbose_name='chi tiết hành động')),
                ('log_timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='thời điểm ghi log')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='địa chỉ IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='user agent')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='loại đối tượng bị tác động')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='người dùng thực hiện')),
            ],
            options={
                'verbose_name': 'nhật ký hoạt động',
                'verbose_name_plural': 'danh sách nhật ký hoạt động',
                'ordering': ['-log_timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='activity_lo_content_50462e_idx'), models.Index(fields=['log_timestamp'], name='activity_lo_log_tim_80442e_idx'), models.Index(fields=['user', 'action'], name='activity_lo_user_id_8864e1_idx')],
            },
        ),
    ]
