"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dotenv
import os
dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',         # Nếu bạn vẫn dùng, giữ lại
    'crispy_tailwind',      # Nếu bạn vẫn dùng, giữ lại
    'apps.accounts.apps.AccountsConfig',
    'apps.patients.apps.PatientsConfig',
    'apps.medical_records.apps.MedicalRecordsConfig',
    'apps.labtests.apps.LabtestsConfig',
    'apps.appointments.apps.AppointmentsConfig',
    'apps.attachments.apps.AttachmentsConfig',
    'apps.activity_logs.apps.ActivityLogsConfig',
    'apps.dashboard.apps.DashboardConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # <<< THÊM MIDDLEWARE NÀY ĐỂ HỖ TRỢ ĐA NGÔN NGỮ TỐT HƠN
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'  # <<< ĐÃ THAY ĐỔI

TIME_ZONE = 'Asia/Ho_Chi_Minh' # <<< ĐÃ THAY ĐỔI

USE_I18N = True

USE_L10N = True # (Trong Django 5.0+ gọi là USE_FORMAT_L10N, nhưng USE_L10N vẫn hoạt động và bao hàm nó)
                # Đảm bảo là True để định dạng ngày tháng, số theo locale.

USE_TZ = True


# (Tùy chọn) Nếu bạn muốn hỗ trợ nhiều ngôn ngữ và cho phép người dùng chọn
# from django.utils.translation import gettext_lazy as _
# LANGUAGES = [
#     ('vi', _('Tiếng Việt')),
#     ('en', _('English')),
# ]
# Thư mục chứa các file .po và .mo cho việc dịch thuật
# LOCALE_PATHS = [
#     BASE_DIR / 'locale',
# ]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# (Tùy chọn) Nếu bạn có các tệp tĩnh chung cho toàn bộ dự án không thuộc app nào
# STATICFILES_DIRS = [
#     BASE_DIR / "static_project_level", 
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

# Cấu hình cho django-crispy-forms (nếu bạn vẫn giữ lại)
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Cài đặt cho Login (nếu bạn tạo trang login riêng sau này)
# LOGIN_URL = 'accounts:login' # Ví dụ
# LOGIN_REDIRECT_URL = 'dashboard:dashboard_home' # Ví dụ
# LOGOUT_REDIRECT_URL = 'dashboard:dashboard_home' # Ví dụ

