# Generated by Django 5.2.1 on 2025-05-16 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='họ và tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=10, null=True, verbose_name='giới tính')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email')),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='nhóm máu')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='dị ứng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL, verbose_name='người cập nhật')),
            ],
            options={
                'verbose_name': 'bệnh nhân',
                'verbose_name_plural': 'danh sách bệnh nhân',
                'ordering': ['full_name'],
            },
        ),
    ]
