# Generated by Django 5.2.1 on 2025-05-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nhập họ tên bệnh nhân', max_length=255, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=50, verbose_name='Số điện thoại liên hệ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Giới tính')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='Nhóm máu')),
                ('allergies', models.TextField(blank=True, verbose_name='Dị ứng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Danh sách bệnh nhân',
                'ordering': ('-created_at',),
            },
        ),
    ]
