# Generated by Django 5.2.1 on 2025-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_date_of_birth_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ma_benh_nhan',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='mã bệnh nhân'),
        ),
    ]
