# Generated by Django 5.2.1 on 2025-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(
                max_length=8,
                null=True,
                blank=True,
                verbose_name='Mã bệnh nhân',
                help_text='Mã số 8 chữ số của bệnh nhân',
            ),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor',
            field=models.CharField(blank=True, help_text='Tên bác sĩ chỉ định xét nghiệm', max_length=255, verbose_name='Bác sĩ chỉ định'),
        ),
    ]
