# Generated by Django 5.2.1 on 2025-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_populate_existing_ma_benh_nhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ma_benh_nhan',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='mã bệnh nhân'),
        ),
    ]
