# Generated by Django 5.2.1 on 2025-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_assign_patient_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(default=1, help_text='Mã số 8 chữ số của bệnh nhân', max_length=8, unique=True, verbose_name='Mã bệnh nhân'),
            preserve_default=False,
        ),
    ]
