# Generated by Django 5.2.1 on 2025-05-17 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='ngày hẹn')),
                ('appointment_time', models.TimeField(blank=True, null=True, verbose_name='giờ hẹn')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='trạng thái lịch hẹn')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ghi chú cho lịch hẹn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo lịch')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật lịch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='người tạo lịch hẹn')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='bệnh nhân')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_appointments', to=settings.AUTH_USER_MODEL, verbose_name='nhân viên (bác sĩ/KTV)')),
            ],
            options={
                'verbose_name': 'lịch hẹn',
                'verbose_name_plural': 'danh sách lịch hẹn',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
